# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages
#sudo: required
#dist: bionic
addons:
  apt:
    packages:
      - libpng-dev
      - libfreetype6-dev
      - libglu1-mesa-dev
      - libgl1-mesa-dev
      - libx11-dev
      - libxt-dev
      - x11proto-core-dev
      - autotools-dev
      
repos:
  CRAN: https://cloud.r-project.org

r_binary_packages:
 - rgl
 - Rcpp
 - RcppEigen
 - RcppArmadillo
 - morpho

notifications:
  email:
    on_success: change
    on_failure: change
