// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/Rvcg.h"
#include <RcppEigen.h>
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dijkstra
std::vector<float> dijkstra(MyMesh& m, std::vector<int> verts, float maxdist);
static SEXP _Rvcg_dijkstra_try(SEXP mSEXP, SEXP vertsSEXP, SEXP maxdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< MyMesh& >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type verts(vertsSEXP);
    Rcpp::traits::input_parameter< float >::type maxdist(maxdistSEXP);
    rcpp_result_gen = Rcpp::wrap(dijkstra(m, verts, maxdist));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Rvcg_dijkstra(SEXP mSEXP, SEXP vertsSEXP, SEXP maxdistSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Rvcg_dijkstra_try(mSEXP, vertsSEXP, maxdistSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _Rvcg_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("std::vector<float>(*dijkstra)(MyMesh&,std::vector<int>,float)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _Rvcg_RcppExport_registerCCallable() { 
    R_RegisterCCallable("Rvcg", "_Rvcg_dijkstra", (DL_FUNC)_Rvcg_dijkstra_try);
    R_RegisterCCallable("Rvcg", "_Rvcg_RcppExport_validate", (DL_FUNC)_Rvcg_RcppExport_validate);
    return R_NilValue;
}
