# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dijkstra <- function(m, verts, maxdist) {
    .Call(`_Rvcg_dijkstra`, m, verts, maxdist)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_Rvcg_RcppExport_registerCCallable', PACKAGE = 'Rvcg')
})
